### ISSUE TITLE
哈喽，最近在做相似的研究，发现模型的梯度并没有下降呢

### ISSUE THREAD

**Issue by Flionay** [sfsun67/GraphCast-from-Ground-Zero#1]
我这里使用的是optax包里的Adam优化器对参数进行更新，发现模型并没有下降...

**Comment by sfsun67** [comment]
Hi~,

我看到了你的 Issue，但是我现在没有做很深入。所以没有注意到模型是否使用 optax 包里的 Adam 优化器对参数进行更新。

但是我重写模型的训练代码后，可以看到模型的 loss 和梯度是下降的。所以，可以试试，将 Demo 的训练部分写成循环的形式。是否可以得到 loss  下降的结果。

（也可能， loss 没下降的原因是使用了相同的训练数据集训练模型。如果是这个问题，试着用不同的 batch 来训练模型。）

祝顺利！
